//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_7.RecreationAreaServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/RecreationAreaService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecreationAreaServiceRef.IRecreationAreaService")]
    public interface IRecreationAreaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecreationAreaService/GetRecreationAreas", ReplyAction="http://tempuri.org/IRecreationAreaService/GetRecreationAreasResponse")]
        string GetRecreationAreas(string query, string states);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecreationAreaService/GetRecreationAreas", ReplyAction="http://tempuri.org/IRecreationAreaService/GetRecreationAreasResponse")]
        System.Threading.Tasks.Task<string> GetRecreationAreasAsync(string query, string states);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecreationAreaService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRecreationAreaService/GetDataUsingDataContractResponse")]
        Assignment_7.RecreationAreaServiceRef.CompositeType GetDataUsingDataContract(Assignment_7.RecreationAreaServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecreationAreaService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRecreationAreaService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Assignment_7.RecreationAreaServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_7.RecreationAreaServiceRef.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecreationAreaServiceChannel : Assignment_7.RecreationAreaServiceRef.IRecreationAreaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecreationAreaServiceClient : System.ServiceModel.ClientBase<Assignment_7.RecreationAreaServiceRef.IRecreationAreaService>, Assignment_7.RecreationAreaServiceRef.IRecreationAreaService {
        
        public RecreationAreaServiceClient() {
        }
        
        public RecreationAreaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecreationAreaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecreationAreaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecreationAreaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRecreationAreas(string query, string states) {
            return base.Channel.GetRecreationAreas(query, states);
        }
        
        public System.Threading.Tasks.Task<string> GetRecreationAreasAsync(string query, string states) {
            return base.Channel.GetRecreationAreasAsync(query, states);
        }
        
        public Assignment_7.RecreationAreaServiceRef.CompositeType GetDataUsingDataContract(Assignment_7.RecreationAreaServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Assignment_7.RecreationAreaServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_7.RecreationAreaServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
