//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_4_5.PhoneNotificationServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PhoneNotificationService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneNotificationServiceRef.IPhoneNotificationService")]
    public interface IPhoneNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/sendPhoneNotificationText", ReplyAction="http://tempuri.org/IPhoneNotificationService/sendPhoneNotificationTextResponse")]
        string sendPhoneNotificationText(string phoneNumber, string newTemperature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/sendPhoneNotificationText", ReplyAction="http://tempuri.org/IPhoneNotificationService/sendPhoneNotificationTextResponse")]
        System.Threading.Tasks.Task<string> sendPhoneNotificationTextAsync(string phoneNumber, string newTemperature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/decryptPhoneNumber", ReplyAction="http://tempuri.org/IPhoneNotificationService/decryptPhoneNumberResponse")]
        string decryptPhoneNumber(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/decryptPhoneNumber", ReplyAction="http://tempuri.org/IPhoneNotificationService/decryptPhoneNumberResponse")]
        System.Threading.Tasks.Task<string> decryptPhoneNumberAsync(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/registerPhoneNumberNotification", ReplyAction="http://tempuri.org/IPhoneNotificationService/registerPhoneNumberNotificationRespo" +
            "nse")]
        void registerPhoneNumberNotification(string phoneNumber, string carrier, string latLocation, string longLocation, string currentTemperature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/registerPhoneNumberNotification", ReplyAction="http://tempuri.org/IPhoneNotificationService/registerPhoneNumberNotificationRespo" +
            "nse")]
        System.Threading.Tasks.Task registerPhoneNumberNotificationAsync(string phoneNumber, string carrier, string latLocation, string longLocation, string currentTemperature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/encryptPhoneNumber", ReplyAction="http://tempuri.org/IPhoneNotificationService/encryptPhoneNumberResponse")]
        string encryptPhoneNumber(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/encryptPhoneNumber", ReplyAction="http://tempuri.org/IPhoneNotificationService/encryptPhoneNumberResponse")]
        System.Threading.Tasks.Task<string> encryptPhoneNumberAsync(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/GetData", ReplyAction="http://tempuri.org/IPhoneNotificationService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/GetData", ReplyAction="http://tempuri.org/IPhoneNotificationService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPhoneNotificationService/GetDataUsingDataContractResponse")]
        Assignment_4_5.PhoneNotificationServiceRef.CompositeType GetDataUsingDataContract(Assignment_4_5.PhoneNotificationServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneNotificationService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPhoneNotificationService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Assignment_4_5.PhoneNotificationServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_4_5.PhoneNotificationServiceRef.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneNotificationServiceChannel : Assignment_4_5.PhoneNotificationServiceRef.IPhoneNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneNotificationServiceClient : System.ServiceModel.ClientBase<Assignment_4_5.PhoneNotificationServiceRef.IPhoneNotificationService>, Assignment_4_5.PhoneNotificationServiceRef.IPhoneNotificationService {
        
        public PhoneNotificationServiceClient() {
        }
        
        public PhoneNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendPhoneNotificationText(string phoneNumber, string newTemperature) {
            return base.Channel.sendPhoneNotificationText(phoneNumber, newTemperature);
        }
        
        public System.Threading.Tasks.Task<string> sendPhoneNotificationTextAsync(string phoneNumber, string newTemperature) {
            return base.Channel.sendPhoneNotificationTextAsync(phoneNumber, newTemperature);
        }
        
        public string decryptPhoneNumber(string phoneNumber) {
            return base.Channel.decryptPhoneNumber(phoneNumber);
        }
        
        public System.Threading.Tasks.Task<string> decryptPhoneNumberAsync(string phoneNumber) {
            return base.Channel.decryptPhoneNumberAsync(phoneNumber);
        }
        
        public void registerPhoneNumberNotification(string phoneNumber, string carrier, string latLocation, string longLocation, string currentTemperature) {
            base.Channel.registerPhoneNumberNotification(phoneNumber, carrier, latLocation, longLocation, currentTemperature);
        }
        
        public System.Threading.Tasks.Task registerPhoneNumberNotificationAsync(string phoneNumber, string carrier, string latLocation, string longLocation, string currentTemperature) {
            return base.Channel.registerPhoneNumberNotificationAsync(phoneNumber, carrier, latLocation, longLocation, currentTemperature);
        }
        
        public string encryptPhoneNumber(string phoneNumber) {
            return base.Channel.encryptPhoneNumber(phoneNumber);
        }
        
        public System.Threading.Tasks.Task<string> encryptPhoneNumberAsync(string phoneNumber) {
            return base.Channel.encryptPhoneNumberAsync(phoneNumber);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Assignment_4_5.PhoneNotificationServiceRef.CompositeType GetDataUsingDataContract(Assignment_4_5.PhoneNotificationServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Assignment_4_5.PhoneNotificationServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_4_5.PhoneNotificationServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
