//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberSortServiceApp.NumberSortServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/NumberSortService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberSortServiceRef.INumberSortService")]
    public interface INumberSortService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/GetData", ReplyAction="http://tempuri.org/INumberSortService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/GetData", ReplyAction="http://tempuri.org/INumberSortService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/INumberSortService/GetDataUsingDataContractResponse")]
        NumberSortServiceApp.NumberSortServiceRef.CompositeType GetDataUsingDataContract(NumberSortServiceApp.NumberSortServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/INumberSortService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<NumberSortServiceApp.NumberSortServiceRef.CompositeType> GetDataUsingDataContractAsync(NumberSortServiceApp.NumberSortServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/sortString", ReplyAction="http://tempuri.org/INumberSortService/sortStringResponse")]
        string sortString(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSortService/sortString", ReplyAction="http://tempuri.org/INumberSortService/sortStringResponse")]
        System.Threading.Tasks.Task<string> sortStringAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberSortServiceChannel : NumberSortServiceApp.NumberSortServiceRef.INumberSortService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberSortServiceClient : System.ServiceModel.ClientBase<NumberSortServiceApp.NumberSortServiceRef.INumberSortService>, NumberSortServiceApp.NumberSortServiceRef.INumberSortService {
        
        public NumberSortServiceClient() {
        }
        
        public NumberSortServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberSortServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberSortServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberSortServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public NumberSortServiceApp.NumberSortServiceRef.CompositeType GetDataUsingDataContract(NumberSortServiceApp.NumberSortServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<NumberSortServiceApp.NumberSortServiceRef.CompositeType> GetDataUsingDataContractAsync(NumberSortServiceApp.NumberSortServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string sortString(string s) {
            return base.Channel.sortString(s);
        }
        
        public System.Threading.Tasks.Task<string> sortStringAsync(string s) {
            return base.Channel.sortStringAsync(s);
        }
    }
}
