//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_6.XmlXsdValidatorServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/XMLXSDValidatorService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmlXsdValidatorServiceRef.IXMLXSDValidatorService")]
    public interface IXMLXSDValidatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/GetData", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/GetData", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/ValidateXMLToXSD", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/ValidateXMLToXSDResponse")]
        string ValidateXMLToXSD(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/ValidateXMLToXSD", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/ValidateXMLToXSDResponse")]
        System.Threading.Tasks.Task<string> ValidateXMLToXSDAsync(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/GetDataUsingDataContractResponse")]
        Assignment_6.XmlXsdValidatorServiceRef.CompositeType GetDataUsingDataContract(Assignment_6.XmlXsdValidatorServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXMLXSDValidatorService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IXMLXSDValidatorService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Assignment_6.XmlXsdValidatorServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_6.XmlXsdValidatorServiceRef.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXMLXSDValidatorServiceChannel : Assignment_6.XmlXsdValidatorServiceRef.IXMLXSDValidatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XMLXSDValidatorServiceClient : System.ServiceModel.ClientBase<Assignment_6.XmlXsdValidatorServiceRef.IXMLXSDValidatorService>, Assignment_6.XmlXsdValidatorServiceRef.IXMLXSDValidatorService {
        
        public XMLXSDValidatorServiceClient() {
        }
        
        public XMLXSDValidatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XMLXSDValidatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLXSDValidatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XMLXSDValidatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string ValidateXMLToXSD(string xmlUrl, string xsdUrl) {
            return base.Channel.ValidateXMLToXSD(xmlUrl, xsdUrl);
        }
        
        public System.Threading.Tasks.Task<string> ValidateXMLToXSDAsync(string xmlUrl, string xsdUrl) {
            return base.Channel.ValidateXMLToXSDAsync(xmlUrl, xsdUrl);
        }
        
        public Assignment_6.XmlXsdValidatorServiceRef.CompositeType GetDataUsingDataContract(Assignment_6.XmlXsdValidatorServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Assignment_6.XmlXsdValidatorServiceRef.CompositeType> GetDataUsingDataContractAsync(Assignment_6.XmlXsdValidatorServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
