//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptocurrencyWebApp.CryptocurrencyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptocurrencyService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCryptocurrencyPrice", ReplyAction="http://tempuri.org/IService/GetCryptocurrencyPriceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        string GetCryptocurrencyPrice(string cryptoTicker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCryptocurrencyPrice", ReplyAction="http://tempuri.org/IService/GetCryptocurrencyPriceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        System.Threading.Tasks.Task<string> GetCryptocurrencyPriceAsync(string cryptoTicker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CryptocurrencyWebApp.CryptocurrencyService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CryptocurrencyWebApp.CryptocurrencyService.IService>, CryptocurrencyWebApp.CryptocurrencyService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCryptocurrencyPrice(string cryptoTicker) {
            return base.Channel.GetCryptocurrencyPrice(cryptoTicker);
        }
        
        public System.Threading.Tasks.Task<string> GetCryptocurrencyPriceAsync(string cryptoTicker) {
            return base.Channel.GetCryptocurrencyPriceAsync(cryptoTicker);
        }
    }
}
