//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INumberGuess")]
public interface INumberGuess
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/SecretNumber", ReplyAction="http://tempuri.org/INumberGuess/SecretNumberResponse")]
    int SecretNumber(int upper, int lower);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/SecretNumber", ReplyAction="http://tempuri.org/INumberGuess/SecretNumberResponse")]
    System.Threading.Tasks.Task<int> SecretNumberAsync(int upper, int lower);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/CheckNumber", ReplyAction="http://tempuri.org/INumberGuess/CheckNumberResponse")]
    string CheckNumber(int userNum, int secretNum);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberGuess/CheckNumber", ReplyAction="http://tempuri.org/INumberGuess/CheckNumberResponse")]
    System.Threading.Tasks.Task<string> CheckNumberAsync(int userNum, int secretNum);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INumberGuessChannel : INumberGuess, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NumberGuessClient : System.ServiceModel.ClientBase<INumberGuess>, INumberGuess
{
    
    public NumberGuessClient()
    {
    }
    
    public NumberGuessClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NumberGuessClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NumberGuessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NumberGuessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int SecretNumber(int upper, int lower)
    {
        return base.Channel.SecretNumber(upper, lower);
    }
    
    public System.Threading.Tasks.Task<int> SecretNumberAsync(int upper, int lower)
    {
        return base.Channel.SecretNumberAsync(upper, lower);
    }
    
    public string CheckNumber(int userNum, int secretNum)
    {
        return base.Channel.CheckNumber(userNum, secretNum);
    }
    
    public System.Threading.Tasks.Task<string> CheckNumberAsync(int userNum, int secretNum)
    {
        return base.Channel.CheckNumberAsync(userNum, secretNum);
    }
}
